### ISSUE TITLE
I have run into a problem

### ISSUE THREAD

**Issue by Aj-AB** [c17hawke/simple-dvc-demo#5]
In the conftest.py file:

import pytest
import yaml
import os
import json

@pytest.fixture
def config(config_path="params.yaml"):
    with open(config_path) as yaml_file:
        config = yaml.safe_load(yaml_file)
    return config

@pytest.fixture
def schema_in(schema_path="schema_in.json"):
    with open(schema_path) as json_file:
        schema = json.load(json_file)
    return schema

**when i push it to github in Action get the error:**

![yaml error](https://user-images.githubusercontent.com/77153457/170817611-cc5e4202-15b1-47c2-9c4b-6926cb49a74e.png)

please help

**Comment by c17hawke** [comment]
You just need to add PyYAML into your requirements.txt file. I've updated mine. @Aj-AB
